name: Realese

run-name: Release triggered by ${{ github.actor }} 😎

on:
    push:
        tags:
            - v* #wird nur ausgeführt, wenn ein Tag erstellt wird, der mit v beginnt
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Create Release
              env:
               GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               TAG: ${{ github.ref_name }}
              run: |
               gh release create "$TAG" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title "Release ${TAG#v}" \
                  --generate-notes
